Sublime/Default (Linux).sublime-keymap: .config/sublime-text-2/Packages/User/Default
  (Linux).sublime-keymap
Sublime/Default (OSX).sublime-keymap: .config/sublime-text-2/Packages/User/Default
  (OSX).sublime-keymap
Sublime/Default (Windows).sublime-keymap: .config/sublime-text-2/Packages/User/Default
  (Windows).sublime-keymap
Sublime/Preferences.sublime-settings: .config/sublime-text-2/Packages/User/Preferences.sublime-settings
bashrc.dotfile: .bashrc
gitconfig.dotfile: .gitconfig
